### ISSUE TITLE
[ANDROID] Separation of concerns in android code 

### ISSUE THREAD

**Issue by thesurajkamble** [shashwatwork/Heart_Disease_prediction#4]
implementing MVC like architecture  to separate the concerns.

**Comment by thesurajkamble** [comment]
hi there , please do review and mark the issues and pull request as "hacktoberfest" approved.
else it wont be counted towards hacktoberfest contribution.

**Comment by shashwatwork** [comment]
@sathickibrahims18  pls review the pull request by @surajkamblesk  and merge

**Comment by thesurajkamble** [comment]
> @sathickibrahims18  pls review the pull request by @surajkamblesk  and merge

@shashwatwork @sathickibrahims18 

Im workin on fixing issue #7 .
The repo isnt marked as 'hacktoberfest' pls mark it the same.
